---
- name: install package on the linux server
  hosts: all
#  user: docker
#  become: true  
  vars_files:
    - vars/common_vars.yml
    - vars/cred.yml
  tasks:
  - name: Install required packages in labs servers  from tower
    yum:
      name: "{{ pkg_name }}"
      state: present
  - name: start services
    service:
      name: "{{ service_name }}"
      state: "{{ service_status }}"
      enabled: true 
